### ISSUE TITLE
cannot type with "keyi"

### ISSUE THREAD

**Issue by zongou** [dongyuwei/web-pinyin-ime#9]
cannot type with "keyi", web page goes into blank.

**Comment by qq1767899088** [comment]
it works for me,it should do the same for you if you set everything correctly.
follow every step in the readme file inside the ime folder,not the one in the web_pinyin_ime folder.
i bet you did not set the yarn thing properly,
cd to ime directory,run every instruction in the readme file, do some google yourself,try to figure everything out.
it would be better if you can provide some screenshots

**Comment by dongyuwei** [comment]
hi @zongou, thanks for your bug report. I've fixed it, please visit https://dongyuwei.github.io/web-pinyin-ime/ and try again. The bug-fix commit is https://github.com/dongyuwei/web-pinyin-ime/commit/74d77ae2012b40f5e1328a2ded565b6e2e8fa413.
